#run it 
name: CI/CD Pipeline for Housing Price Prediction

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
  pull_request:
    branches:
      - main
    paths:
      - 'MLProject/**'

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Miniconda and Create/Activate Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12
        channels: conda-forge,defaults
        environment-file: MLProject/conda.yaml
        activate-environment: housing-price-prediction-env # This activates the env for subsequent steps
        auto-activate-base: false

    - name: Install MLflow (if not in conda.yaml)
      # This step is still good to ensure mlflow is installed in the activated env
      # especially if it's not explicitly in your conda.yaml file.
      run: |
        pip install mlflow
      # The shell is automatically configured by setup-miniconda

    - name: Start MLflow Tracking Server
      run: |
        nohup mlflow server --host 127.0.0.1 --port 5000 --backend-store-uri sqlite:///mlruns.db &
        sleep 5
      shell: bash

    - name: Run MLflow Project
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:5000
      run: |
        # Use --no-conda flag because the environment is already active
        mlflow run MLProject -e main --no-conda 
      # The shell is automatically configured by setup-miniconda

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-artifacts
        path: mlruns/
