name: CI/CD Pipeline for Housing Price Prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12 # Ensure this matches your project's Python version
        channels: conda-forge,defaults

    - name: Create and activate Conda environment
      run: |
        conda env create -f MLProject/conda.yml # Assuming you have an conda.yml
        conda activate housing-price-prediction-env # Replace with the actual name of your environment if different

    - name: Install MLflow (if not in conda.yml)
      run: |
        conda activate housing-price-prediction-env
        pip install mlflow

    - name: Start MLflow Tracking Server
      run: |
        # Use nohup to run in background and redirect output to prevent hanging
        # Using a simple SQLite backend for local testing within the runner
        nohup mlflow server --host 127.0.0.1 --port 5000 --backend-store-uri sqlite:///mlruns.db &
        # Give the server a moment to start up
        sleep 5 
      shell: bash # Ensure bash shell is used for `nohup` and `&`

    - name: Run MLflow Project
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:5000 # Explicitly set for the project run
      run: |
        conda activate housing-price-prediction-env
        mlflow run MLProject -e main # Or adjust to your entry point if it's not 'main'
