name: MLflow Project CI Training

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda & create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          python-version: '3.12'
          environment-file: MLProject/conda.yaml
          activate-environment: housing-price-prediction-env

      - name: Run MLflow Project
        shell: bash -l {0}  # penting untuk mengaktifkan conda env
        run: |
          mlflow run MLProject/
        env:
          MLFLOW_TRACKING_URI: 'file:./mlruns'

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-artifacts
          path: mlruns/
